# Generated by Django 5.1.5 on 2025-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_feature', '0002_message_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
